import {useEffect,useState} from "react";

export const DEVELOPER_URL="https://www.youtube.com/@NYXOPLAYZ";
const PENDING_KEY="auto-publisher-developer-subscribe-pending";
const SHOWN_KEY="auto-publisher-developer-achievement-shown";

export function markDeveloperSubscribe(){localStorage.setItem(PENDING_KEY,String(Date.now()));window.open(DEVELOPER_URL,"_blank","noopener,noreferrer");}

export function SubscribeDeveloper({compact=false}){return <button type="button" onClick={markDeveloperSubscribe} className={compact?"group flex w-full items-center gap-3 rounded-xl border-white/10 bg-white/[.025] p-3 text-left transition hover:border-white/20 hover:bg-white/[.06]":"panel dashboard-card flex items-center gap-4 p-4 text-left"}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#ff0033] text-white" aria-hidden="true"><svg viewBox="0 0 24 24" className="h-5 w-5 fill-current"><path d="M23.5 6.2a3 3 0 0 0-2.1-2.1C19.5 3.6 12 3.6 12 3.6s-7.5 0-9.4.5A3 3 0 0 0 .5 6.2 31 31 0 0 0 0 12a31 31 0 0 0 .5 5.8 3 3 0 0 0 2.1 2.1c1.9.5 9.4.5 9.4.5s7.5 0 9.4-.5a3 3 0 0 0 2.1-2.1A31 31 0 0 0 24 12a31 31 0 0 0-.5-5.8ZM9.6 15.6V8.4l6.3 3.6-6.3 3.6Z"/></svg></span><span><span className="block text-sm font-semibold">Subscribe to Developer</span><span className="mt-1 block text-xs text-neutral-500">Support the developer ❤️</span></span></button>}

export function AchievementToast(){const [visible,setVisible]=useState(false);useEffect(()=>{const check=()=>{const pending=localStorage.getItem(PENDING_KEY);if(pending&&!localStorage.getItem(SHOWN_KEY)&&Date.now()-Number(pending)<86400000){localStorage.setItem(SHOWN_KEY,"1");localStorage.removeItem(PENDING_KEY);setVisible(true);window.setTimeout(()=>setVisible(false),5000)}};window.addEventListener("focus",check);document.addEventListener("visibilitychange",check);return()=>{window.removeEventListener("focus",check);document.removeEventListener("visibilitychange",check)}} ,[]);if(!visible)return null;return <div className="achievement-toast fixed right-4 top-20 z-50 w-[min( calc(100vw - 2rem), 22rem)] rounded-2xl border-white/20 bg-[#101010]/95 p-4 text-white shadow-[0_20px_70px_rgba(0,0,0,.55)] backdrop-blur-xl" role="status"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl border-white/20 bg-white/10 text-lg">★</span><div><div className="text-[10px] font-bold uppercase tracking-[.18em] text-neutral-400">Achievement Unlocked!</div><div className="mt-1 font-display text-sm font-semibold">Subscribe to Developer</div></div></div></div>}
