import {useEffect,useState} from "react"; import Layout from "../components/Layout"; import CategoryManager from "../components/CategoryManager"; import apiClient from "../api/client"; import {generateAccessCode,listAccessCodes} from "../api/access";
const rows=[["total_drive_sources","Drive sources","◫"],["total_discovered_videos","Discovered videos","▶"],["connected_youtube_channels","Connected channels","◎"],["todays_uploads","Today's uploads","↗"],["failed_uploads","Unresolved failures","!"]];
function Status({value}){return <span className={`rounded-full border px-2.5 py-1 text-[10px] font-bold tracking-wider ${value==="success"?"border-white/15 bg-white/10 text-white":value==="partial"?"border-white/15 bg-white/5 text-neutral-300":"border-red-300/20 bg-red-300/5 text-red-200"}`}>{String(value).replaceAll("_"," ").toUpperCase()}</span>}
export default function AdminDashboard(){const[data,setData]=useState(null),[health,setHealth]=useState(null),[runs,setRuns]=useState([]),[codes,setCodes]=useState([]),[newCode,setNewCode]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[actionError,setActionError]=useState("");
const detail=e=>e?.response?.data?.detail||e?.message||"Request failed.";
async function refresh(){setBusy(true);setError("");const results=await Promise.allSettled([apiClient.get("/api/admin/dashboard"),apiClient.get("/api/admin/health-summary"),apiClient.get("/api/admin/automation/runs?limit=20"),listAccessCodes()]);const [d,h,r,c]=results;if(d.status==="fulfilled")setData(d.value.data);if(h.status==="fulfilled")setHealth(h.value.data);if(r.status==="fulfilled")setRuns(r.value.data);if(c.status==="fulfilled")setCodes(c.value);const failed=results.filter(x=>x.status==="rejected");if(failed.length)setError(failed.map(x=>detail(x.reason)).join(" · "));setBusy(false)}useEffect(()=>{refresh()},[]);
async function createCode(){setActionError("");try{const x=await generateAccessCode();setNewCode(x.code);setCodes(await listAccessCodes())}catch(e){setActionError(detail(e))}}
return <Layout><div className="mx-auto max-w-7xl px-5 py-8 lg:px-10 lg:py-12"><header className="reveal flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="eyebrow">SYSTEM / OVERVIEW</div><h1 className="mt-3 font-display text-4xl font-bold tracking-tight sm:text-6xl">Control room.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-neutral-500">Monitor your content pipeline, sources, channels and automation from one place.</p></div><button onClick={refresh} disabled={busy} className="btn-ghost px-4 py-2.5 text-xs disabled:opacity-50">{busy?"Refreshing…":"↻ Refresh system"}</button></header>
{error&&<div className="mt-6 rounded-2xl border border-red-400/20 bg-red-400/5 p-4 text-sm text-red-200">Some admin data could not be loaded: {error}<button onClick={refresh} className="ml-3 underline">Retry</button></div>}
<div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{rows.map(([k,l,ic],i)=><div key={k} className="panel dashboard-card p-5"><div className="flex justify-between"><span className="text-neutral-600">{ic}</span><span className="text-[10px] text-neutral-700">0{i+1}</span></div><div className="mt-9 text-3xl font-display font-bold">{data?data[k]:"—"}</div><p className="mt-1 text-xs text-neutral-500">{l}</p></div>)}</div>
<div className="mt-6 grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><section className="panel p-6"><div className="flex items-end justify-between"><div><div className="eyebrow">AUTOMATION</div><h2 className="mt-2 font-display text-2xl font-semibold">Recent runs</h2></div><span className="text-xs text-neutral-600">One run / channel / day</span></div><div className="mt-6 space-y-2">{runs.length===0?<p className="py-8 text-sm text-neutral-500">No automation runs yet.</p>:runs.map(r=><div key={r.id} className="flex items-center justify-between rounded-2xl border border-white/8 bg-white/[.025] p-4"><div><p className="text-sm font-semibold">{r.run_date}</p><p className="mt-1 text-xs text-neutral-500">{r.videos_uploaded}/{r.videos_attempted} uploaded</p></div><Status value={r.status}/></div>)}</div></section>
<section className="panel p-6"><div className="eyebrow">ACCESS</div><h2 className="mt-2 font-display text-2xl font-semibold">User access codes</h2><p className="mt-2 text-sm leading-6 text-neutral-500">One-time grants for admin-managed credentials.</p><button onClick={createCode} disabled={busy} className="btn-primary mt-6 w-full py-3 disabled:opacity-50">Generate one-time code</button>{actionError&&<p className="mt-3 rounded-xl border-red-400/20 bg-red-400/5 p-3 text-xs text-red-200">{actionError}</p>}{newCode&&<div className="mt-4 rounded-2xl border border-white/15 bg-white/5 p-4"><div className="text-[10px] uppercase tracking-widest text-neutral-500">Copy now — shown once</div><div className="mt-2 flex gap-2"><code className="flex-1 break-all text-sm">{newCode}</code><button onClick={()=>navigator.clipboard.writeText(newCode)} className="btn-ghost px-3 text-xs">Copy</button></div></div>}<div className="mt-5 space-y-2">{codes.map(x=><div key={x.id} className="flex justify-between rounded-xl border border-white/8 p-3 text-xs"><span className="text-neutral-400">{x.status}</span><span className="text-neutral-600">{new Date(x.created_at).toLocaleDateString()}</span></div>)}</div></section></div>
<div className="mt-6 grid gap-3 sm:grid-cols-3">{health&&Object.entries(health).map(([k,v])=><div key={k} className="panel-soft p-4"><p className="text-[10px] uppercase tracking-widest text-neutral-600">{k.replaceAll("_"," ")}</p><p className="mt-2 font-display text-xl">{String(v)}</p></div>)}</div><p className="mt-5 text-xs text-neutral-600">Scheduler: {data?.automation_status||"status unavailable"}</p><CategoryManager/></div></Layout>}
